//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPasswords
    {
        public System.Guid uidPasswordID { get; set; }
        public System.Guid uidPersonID { get; set; }
        public string strPassword { get; set; }
        public string strNumber { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
    }
}
